import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const styleDir = path.join(process.cwd(), "src", "style");
const indexPath = path.join(styleDir, "index.css");
const outPath = path.join(process.cwd(), "styles.css");

const indexContent = fs.readFileSync(indexPath, "utf8");
const importRe = /^@import\s+"(.+?)";\s*$/gm;

const registered = new Set();
let match;
let output = `/* Generated by scripts/build-css.mjs - do not edit directly. Edit files under src/style/ instead. */\n\n`;

while ((match = importRe.exec(indexContent)) !== null) {
  const relPath = match[1];
  registered.add(relPath);
  const filePath = path.join(styleDir, relPath);
  if (!fs.existsSync(filePath)) {
    throw new Error(`[build-css] ${relPath} is imported in index.css but does not exist`);
  }
  output += `/* --- ${relPath} --- */\n`;
  output += fs.readFileSync(filePath, "utf8");
  output += "\n";
}

function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      walk(full);
    } else if (entry.name.endsWith(".css")) {
      const rel = path.relative(styleDir, full).split(path.sep).join("/");
      if (rel === "index.css") continue;
      if (!registered.has(rel)) {
        throw new Error(`[build-css] ${rel} exists under src/style/ but is not imported in index.css`);
      }
    }
  }
}
walk(styleDir);

fs.writeFileSync(outPath, output, "utf8");
console.log(`[build-css] wrote ${outPath} (${registered.size} files)`);
